# Generated by Django 5.1.5 on 2025-01-17 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100, verbose_name='наименование')),
                (
                    'member_type',
                    models.CharField(
                        choices=[
                            ('PLNT', 'plant'),
                            ('INDV', 'individual'),
                            ('RTL', 'retail'),
                        ],
                        max_length=4,
                        verbose_name='тип звена',
                    ),
                ),
                (
                    'accounts_payable',
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name='кредиторка'
                    ),
                ),
                (
                    'created_at',
                    models.DateField(auto_now_add=True, verbose_name='дата создания'),
                ),
                (
                    'updated_at',
                    models.DateField(auto_now=True, verbose_name='дата изменения'),
                ),
                (
                    'supplier',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        to='retail.member',
                        verbose_name='поставщик',
                    ),
                ),
            ],
            options={
                'verbose_name': 'элемент сети',
                'verbose_name_plural': 'элементы сети',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('email', models.EmailField(max_length=254, verbose_name='эл.почта')),
                ('country', models.CharField(max_length=100, verbose_name='страна')),
                ('city', models.CharField(max_length=100, verbose_name='город')),
                ('street', models.CharField(max_length=100, verbose_name='улица')),
                ('building', models.CharField(max_length=100, verbose_name='строение')),
                (
                    'created_at',
                    models.DateField(auto_now_add=True, verbose_name='дата создания'),
                ),
                (
                    'updated_at',
                    models.DateField(auto_now=True, verbose_name='дата изменения'),
                ),
                (
                    'member',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='contacts',
                        to='retail.member',
                        verbose_name='',
                    ),
                ),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'контакты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=100, verbose_name='наименование')),
                (
                    'product_model',
                    models.CharField(max_length=100, verbose_name='модель'),
                ),
                ('launch_date', models.DateField(verbose_name='дата выхода на рынок')),
                (
                    'created_at',
                    models.DateField(auto_now_add=True, verbose_name='дата создания'),
                ),
                (
                    'updated_at',
                    models.DateField(auto_now=True, verbose_name='дата изменения'),
                ),
                (
                    'member',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='products',
                        to='retail.member',
                        verbose_name='',
                    ),
                ),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ['name'],
            },
        ),
    ]
