# Generated by Django 5.1.5 on 2025-01-20 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0002_alter_contact_options_member_member_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='supplier',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='retail.member', verbose_name='поставщик'),
        ),
    ]
