# Generated by Django 5.1.5 on 2025-01-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0004_alter_member_accounts_payable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='need_recalc',
            field=models.BooleanField(
                default=False, editable=False, verbose_name='уровень'
            ),
        ),
    ]
