# Generated by Django 5.1.5 on 2025-01-20 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0005_member_need_recalc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='buyers', to='retail.member', verbose_name='поставщик'),
        ),
    ]
