# Generated by Django 5.1.5 on 2025-01-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0006_alter_member_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='test',
            field=models.BooleanField(default=False),
        ),
    ]
