# Generated by Django 5.1.5 on 2025-01-20 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0007_member_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='test',
        ),
    ]
