# Generated by Django 5.1.5 on 2025-01-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0008_remove_member_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_type',
            field=models.CharField(
                choices=[
                    ('PLNT', 'Завод'),
                    ('INDV', 'Индивидуальный предприниматель'),
                    ('RTL', 'Розничная сеть'),
                ],
                default='PLNT',
                max_length=4,
                verbose_name='тип звена',
            ),
        ),
    ]
