# Generated by Django 5.1.5 on 2025-01-29 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retail", "0009_alter_member_member_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="contact",
            name="city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="город"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="country",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="страна"
            ),
        ),
        migrations.AlterField(
            model_name="member",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="buyers",
                to="retail.member",
                verbose_name="поставщик",
            ),
        ),
    ]
