# Generated by Django 5.1.5 on 2025-01-29 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retail", "0010_city_country_alter_contact_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="retail.city",
                verbose_name="город",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="retail.country",
                verbose_name="страна",
            ),
        ),
    ]
