# Generated by Django 5.1.5 on 2025-01-29 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retail", "0011_alter_contact_city_alter_contact_country"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="city",
            options={"verbose_name": "город", "verbose_name_plural": "города"},
        ),
        migrations.AlterModelOptions(
            name="country",
            options={"verbose_name": "страна", "verbose_name_plural": "страны"},
        ),
        migrations.AlterField(
            model_name="contact",
            name="city",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="retail.city",
                verbose_name="город",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contact",
            name="country",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="retail.country",
                verbose_name="страна",
            ),
            preserve_default=False,
        ),
    ]
